### PR TITLE
Update documentation for private plugins/themes

### PR DESCRIPTION
**Pull request by jamespfarrell**
Update to the readme to detail how to get autoloader to load private plugins, and put them in the correct folder.

### CODE REVIEW

**Comment by tditlu** [comment]
Thank you, maybe we should also reference to the the composer document about path repositories?
https://getcomposer.org/doc/05-repositories.md#path

**Comment by jamespfarrell** [comment]
Good idea, will update and let you know...

**Comment by jamespfarrell** [comment]
ok I have updated the change to include a link to the composer docs...

**Comment by vinkla** [comment]
@jamespfarrell do you use this to load local plugins on your system or external ones?

**Comment by vinkla** [comment]
@jamespfarrell do you use this to load local plugins on your system or external ones?

**Comment by jamespfarrell** [comment]
These are local plugins. This includes premium plugins and our own custom plugins... We have controls in place, that make individual repositories quite time consuming to create, so prefer to keep plugins not managed by wpackagist under our main repo...

**Comment by vinkla** [comment]
Thanks for clarifying and for the pull request.

**Comment by jamespfarrell** [comment]
Thank for all your hard word, and great package and the opportunity to help. Please let me know if you need help with anything!

**Pull request merged**
